add_header X-Server-Time $time_iso8601 always;
add_header X-User-Agent $http_user_agent always;
add_header X-Origin $http_origin always;
add_header X-Client-Country $http_cf_ipcountry always;
add_header Vary Origin always;
