add_header X-Server-Time $time_iso8601 always;
add_header X-User-Agent $http_user_agent always;
add_header X-Origin $http_origin always;
add_header X-Client-Country $http_cf_ipcountry always;
add_header Vary Origin always;

# Strong Security Headers
add_header Content-Security-Policy "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https://tailuge.github.io; connect-src 'self' https://billiards-network.onrender.com wss://billiards.onrender.com https://scoreboard-tailuge.vercel.app https://billiards.tailuge.workers.dev; frame-ancestors 'self'; require-trusted-types-for 'script';" always;
add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
add_header Cross-Origin-Opener-Policy "same-origin" always;
add_header X-Frame-Options "SAMEORIGIN" always;
add_header X-Content-Type-Options "nosniff" always;
add_header Referrer-Policy "strict-origin-when-cross-origin" always;
