server {
    listen       8080;
    listen  [::]:8080;
    server_name  localhost;

    client_max_body_size 1m;
    client_body_buffer_size 64k;

    # Shared configuration (Inherited ONLY if location doesn't define its own headers)
    include /etc/nginx/metadata_headers.conf;

    # Health check endpoint
    location = /health {
        return 200 'OK';
        add_header Content-Type text/plain;
        include /etc/nginx/metadata_headers.conf;
        include /etc/nginx/cors.conf;
    }

    # Publisher endpoint table
    location ~ ^/publish/table/(?<tableId>[\w-]+)$ {
        include /etc/nginx/metadata_headers.conf;
        include /etc/nginx/cors.conf;
        js_content nchan_meta.publish;
    }

    location ~ ^/internal/publish/table/(?<tableId>\w+)$ {
        internal;
        nchan_publisher;
        nchan_channel_id $tableId;
        nchan_message_buffer_length 2000;
        default_type application/json;
    }

    # Publisher endpoint lobby
    location ~ ^/publish/lobby/(?<channel>\w+)$ {
        include /etc/nginx/metadata_headers.conf;
        include /etc/nginx/cors.conf;
        js_content nchan_meta.publish;
    }

    location ~ ^/internal/publish/lobby/(?<channel>\w+)$ {
        internal;
        nchan_publisher;
        nchan_channel_id $channel;
        nchan_message_buffer_length 0;
        default_type application/json;
    }

    # Publisher endpoint presence
    location = /publish/presence/lobby {
        include /etc/nginx/metadata_headers.conf;
        include /etc/nginx/cors.conf;
        js_content nchan_meta.publish;
    }

    location = /internal/publish/presence/lobby {
        internal;
        nchan_publisher;
        nchan_channel_id "presence/lobby";
        nchan_message_buffer_length 2000;
        nchan_message_timeout 90s;
        default_type application/json;
    }

    # Subscriber endpoint table
    location ~ ^/subscribe/table/(?<tableId>[\w-]+)$ {
        access_log /var/log/nginx/access.log main;
        nchan_subscriber;
        nchan_channel_id $tableId;
        nchan_message_buffer_length 0;
        nchan_message_timeout 0;
        nchan_subscriber_first_message oldest;
        nchan_subscriber_timeout 0;

        include /etc/nginx/metadata_headers.conf;
        include /etc/nginx/cors.conf;
    }

    # Subscriber endpoint lobby
    location ~ ^/subscribe/lobby/(?<channel>\w+)$ {
        access_log /var/log/nginx/access.log main;
        nchan_subscriber;
        nchan_channel_id $channel;
        nchan_message_buffer_length 0;
        nchan_message_timeout 0;
        nchan_subscriber_timeout 0;

        include /etc/nginx/metadata_headers.conf;
        include /etc/nginx/cors.conf;
    }

    # Subscriber endpoint presence
    location = /subscribe/presence/lobby {
        access_log /var/log/nginx/access.log main;
        nchan_subscriber;
        nchan_channel_id "presence/lobby";
        nchan_message_buffer_length 2000;
        nchan_message_timeout 90s;
        nchan_subscriber_first_message oldest;
        nchan_subscriber_timeout 0;

        include /etc/nginx/metadata_headers.conf;
        include /etc/nginx/cors.conf;
    }

    # Basic status monitoring
    location = /basic_status {
        stub_status;
        include /etc/nginx/metadata_headers.conf;
        include /etc/nginx/cors.conf;
    }

    # Extended stats
    location /nchan_stats {
        nchan_stub_status;
        include /etc/nginx/metadata_headers.conf;
        include /etc/nginx/cors.conf;
    }

    # Aggregated Stats API
    location = /api/stats {
        js_content nchan_meta.stats;
        include /etc/nginx/metadata_headers.conf;
        include /etc/nginx/cors.conf;
    }

    # Serve static files
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        include /etc/nginx/metadata_headers.conf;
        include /etc/nginx/cors.conf;
    }
}
